### ISSUE TITLE
Channel animation shortcuts don't work on Mac

### ISSUE THREAD

**Issue by nbrunett** [CARTAvis/carta#37] opened 2020-08-19 17:43 UTC
Shortcuts for changing channels in a cube (ctl up/down) do not work on Mac since they are tied to app windowing. I also tried cmd up/down which does nothing.

I'm using macOS 10.15.6.

**Comment by kswang1029** [comment] 2020-08-20 01:41
Are you using the macOS desktop version or using the linux desktop version from a remote server in the remote mode (run the executable with "--remote" flag)? What do you see from "Help"->"Controls and shortcuts"?

With the macOS desktop version, I see
![Screen Shot 2020-08-20 at 9 38 40 AM](https://user-images.githubusercontent.com/20819712/90707050-41e43480-e2c9-11ea-8b30-0d9761de4887.png)
and it works.

**Comment by kswang1029** [comment] 2020-08-20 01:50
OK, if we use linux desktop in the remote with a Mac as client, the issue exists.
![Screen Shot 2020-08-20 at 9 48 15 AM](https://user-images.githubusercontent.com/20819712/90707597-86bc9b00-e2ca-11ea-9287-5452f7b12154.png)
Shortcuts conflict with the default shortcuts of the macOS.

**Comment by kswang1029** [comment] 2020-08-20 02:02
@nbrunett thanks for the feedback. We will address this issue with https://github.com/CARTAvis/carta-frontend/issues/1143

**Comment by Kechil** [comment] 2020-09-21 08:41
Duplicate of #1143

**Closed as completed by Kechil** 2020-09-21 08:41 UTC
