### ISSUE TITLE
Feature Request: Match Clip Min/Clip Max

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta#42] opened 2020-10-27 01:08 UTC
I'd like to view images on the same color stretch, with matched Clip Min / Clip Max & scaling.

It would be nice if this was also configurable from the debug scripted load.

**Comment by kswang1029** [comment] 2020-10-27 01:19
do you mean https://github.com/CARTAvis/carta-frontend/issues/1089?

**Comment by keflavich** [comment] 2020-10-27 01:26
Yes!

**Comment by kswang1029** [comment] 2020-10-27 01:27
Good! This is scheduled in the next release (v2.0).

**Comment by keflavich** [comment] 2020-10-27 01:30
OK, great!

Is there a release schedule?  I see a roadmap, but no schedule, here: https://cartavis.github.io/

**Comment by kswang1029** [comment] 2020-10-27 01:32
it is still under discussions but probably sometime in Spring 2021.

**Comment by veggiesaurus** [comment] 2020-10-27 10:11
closing as duplicate of https://github.com/CARTAvis/carta-frontend/issues/1089

**Closed as completed by veggiesaurus** 2020-10-27 10:11 UTC
