### ISSUE TITLE
Feature request: Select all regions

### ISSUE THREAD

**Issue by jdelhaize2** [CARTAvis/carta#15] opened 2020-04-02 14:44 UTC
Hi there,

I use Carta at the moment mainly for plotting the positions of catalogued sources as regions on top of maps. It would be great to be able to select all regions (or shift/cmd click to select several regions) simultaneously. I'd mainly like to use this feature to delete all regions, or change their colour.

Cheers,
Jacinta

**Comment by veggiesaurus** [comment] 2020-09-21 08:24
duplicate of https://github.com/CARTAvis/carta-frontend/issues/1040

**Closed as completed by veggiesaurus** 2020-09-21 08:24 UTC
