### ISSUE TITLE
statistics values incorrect in regions after applying WCS 'spatial only' matching

### ISSUE THREAD

**Issue by pjmac1105** [CARTAvis/carta#76] opened 2021-04-27 06:10 UTC
When applying WCS matching, the statistics of regions is changing - for example: before WCS spatial matching, the peak pixel value in a region is identical between the statistics widget and what is reported by hovering the mouse over the pixel. However after WCS matching is applied, the values in the statistics widget are incorrect.

The max value in the images below is in the black box centered in the region. 

Tested on CARTA version 1.4.0 (20200914) running on macOS Mojave 10.14.5, and CARTA remote installed on Pawsey.

![image](https://user-images.githubusercontent.com/19280051/116193469-c64d5800-a772-11eb-99e1-5a68463ccfdd.png)
![image](https://user-images.githubusercontent.com/19280051/116193509-d49b7400-a772-11eb-96bc-324273bd010c.png)

**Comment by kswang1029** [comment] 2021-04-27 06:14
could you provide the two images for further investigation?

**Comment by pjmac1105** [comment] 2021-04-27 06:37
the files might be too large to upload, can I grab your email and i'll send a link

**Comment by kswang1029** [comment] 2021-04-27 06:39
@pjmac1105 kswang _AT_ asiaa.sinica.edu.tw thanks.

**Comment by kswang1029** [comment] 2021-04-28 02:48
@pjmac1105 Thanks for the test images. I can reproduce the issue with v1.4. At the current development cycle, we have fixed few region related issues. With our latest dev version, the issue is gone I think. We are working on the coming new release v2.0 targeting early June. The v2.0-beta will be available in mid-May. Will you be interested to test this again with the coming beta release?

**Comment by pjmac1105** [comment] 2021-04-28 05:11
Hi Kuo-Song,

 

Very happy you could find a problem, I would be very interested in testing on the beta release! 

 

Regards

Peter

**Comment by veggiesaurus** [comment] 2021-07-11 09:12
@kswang1029 can we close this?

**Comment by kswang1029** [comment] 2021-07-15 01:49
> @kswang1029 can we close this?

Yes I think the issue fix has been included in the v2.0 release.

**Closed as completed by kswang1029** 2021-07-15 01:49 UTC
